In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv("stock.csv")
df.head()

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low,Sector
0,01-06-2025,AAPL,185.96,187.79,188.85,183.74,42257183,2.931360e+12,28.37,0.49,6.62,248.20,155.68,Technology
1,01-06-2025,ABBV,189.63,193.64,194.31,188.03,33074970,3.289230e+11,16.74,3.51,11.57,210.83,127.91,Healthcare
2,01-06-2025,ABT,118.79,120.08,120.53,118.01,17130934,2.001330e+11,19.39,1.84,6.19,140.79,99.26,Healthcare
3,01-06-2025,ADBE,584.51,567.78,587.97,561.25,11080360,2.460380e+11,43.29,0.00,13.12,727.11,407.82,Technology
4,01-06-2025,ADP,253.46,255.60,258.59,249.91,10319559,1.052470e+11,29.92,2.04,8.54,303.75,234.28,Financials

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [3]:
df_dropped=df.drop(columns=['Date','Ticker','Volume Traded','Sector'])
df_dropped

,Open Price,Close Price,High Price,Low Price,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low
0,185.96,187.79,188.85,183.74,2.931360e+12,28.37,0.49,6.62,248.20,155.68
1,189.63,193.64,194.31,188.03,3.289230e+11,16.74,3.51,11.57,210.83,127.91
2,118.79,120.08,120.53,118.01,2.001330e+11,19.39,1.84,6.19,140.79,99.26
3,584.51,567.78,587.97,561.25,2.460380e+11,43.29,0.00,13.12,727.11,407.82
4,253.46,255.60,258.59,249.91,1.052470e+11,29.92,2.04,8.54,303.75,234.28
...,...,...,...,...,...,...,...,...,...,...
4341,478.20,489.78,491.84,476.65,1.275470e+11,28.64,0.00,17.10,603.57,411.70
4342,46.61,47.75,48.26,46.15,1.856940e+11,9.31,5.82,5.13,53.28,40.22
4343,71.65,70.99,72.35,70.46,5.560060e+11,25.93,1.27,2.74,90.05,62.53
4344,117.02,112.37,118.45,111.41,4.403070e+11,15.72,3.09,7.15,122.66,100.50
4345,146.81,148.32,150.25,145.16,6.723840e+10,29.39,0.74,5.05,184.27,110.21

In [4]:
missing_value = df_dropped.isnull().sum()
print(missing_value)

Open Price        0
Close Price       0
High Price        0
Low Price         0
Market Cap        0
PE Ratio          0
Dividend Yield    0
EPS               0
52 Week High      0
52 Week Low       0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
cols=['Market Cap']
l=LabelEncoder()

for col in cols:
    df[col]=l.fit_transform(df[col])

In [7]:
df

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low,Sector
0,01-06-2025,AAPL,185.96,187.79,188.85,183.74,42257183,4159,28.37,0.49,6.62,248.20,155.68,Technology
1,01-06-2025,ABBV,189.63,193.64,194.31,188.03,33074970,3129,16.74,3.51,11.57,210.83,127.91,Healthcare
2,01-06-2025,ABT,118.79,120.08,120.53,118.01,17130934,2486,19.39,1.84,6.19,140.79,99.26,Healthcare
3,01-06-2025,ADBE,584.51,567.78,587.97,561.25,11080360,2710,43.29,0.00,13.12,727.11,407.82,Technology
4,01-06-2025,ADP,253.46,255.60,258.59,249.91,10319559,500,29.92,2.04,8.54,303.75,234.28,Financials
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4341,23-07-2025,VRTX,478.20,489.78,491.84,476.65,7141573,950,28.64,0.00,17.10,603.57,411.70,Healthcare
4342,23-07-2025,VZ,46.61,47.75,48.26,46.15,9865947,2326,9.31,5.82,5.13,53.28,40.22,Communication Services
4343,23-07-2025,WMT,71.65,70.99,72.35,70.46,22059711,3592,25.93,1.27,2.74,90.05,62.53,Consumer Staples
4344,23-07-2025,XOM,117.02,112.37,118.45,111.41,13557718,3422,15.72,3.09,7.15,122.66,100.50,Energy
4345,23-07-2025,ZTS,146.81,148.32,150.25,145.16,5102989,20,29.39,0.74,5.05,184.27,110.21,Healthcare

In [8]:
df.columns = df.columns.str.strip()

In [9]:
x = df[['Open Price', 'High Price','Low Price', '52 Week High','52 Week Low']]
y = df['Close Price']

In [10]:
x

      Open Price  High Price  Low Price  52 Week High  52 Week Low
0         185.96      188.85     183.74        248.20       155.68
1         189.63      194.31     188.03        210.83       127.91
2         118.79      120.53     118.01        140.79        99.26
3         584.51      587.97     561.25        727.11       407.82
4         253.46      258.59     249.91        303.75       234.28
...          ...         ...        ...           ...          ...
4341      478.20      491.84     476.65        603.57       411.70
4342       46.61       48.26      46.15         53.28        40.22
4343       71.65       72.35      70.46         90.05        62.53
4344      117.02      118.45     111.41        122.66       100.50
4345      146.81      150.25     145.16        184.27       110.21

[4346 rows x 5 columns]

In [11]:
y

0       187.79
1       193.64
2       120.08
3       567.78
4       255.60
         ...
4341    489.78
4342     47.75
4343     70.99
4344    112.37
4345    148.32
Name: Close Price, Length: 4346, dtype: float64

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler

In [13]:
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
import numpy as np

# Example: Convert continuous target to binary labels
# Let's say values above the median are '1' (high), below are '0' (low)
threshold = np.median(y)
y_class = (y > threshold).astype(int)

# Apply RandomOverSampler
osm = RandomOverSampler(random_state=42)
x_r, y_r = osm.fit_resample(x, y_class)

# Train-test split
x_train, x_test, y_train, y_test = train_test_split(x_r, y_r, test_size=0.2, random_state=44)

In [14]:
print(x.shape,x_train.shape,x_test.shape)

(4346, 5) (3476, 5) (870, 5)

In [15]:
print(y.shape,y_train.shape,y_test.shape)

(4346,) (3476,) (870,)

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [17]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,recall_score,f1_score

In [18]:
k=5
knn=KNeighborsClassifier(n_neighbors=k)

In [19]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [20]:
yp=knn.predict(x_test)

In [21]:
accuracy=accuracy_score(y_test,yp)
print(accuracy)

0.993103448275862

In [22]:
c_report=classification_report(y_test,yp)
print(c_report)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       430
           1       0.99      0.99      0.99       440

    accuracy                           0.99       870
   macro avg       0.99      0.99      0.99       870
weighted avg       0.99      0.99      0.99       870

In [23]:
conf_matrix=confusion_matrix(y_test,yp)
print(conf_matrix)

[[427   3]
 [  3 437]]

In [24]:
import numpy as np
from sklearn.model_selection import GridSearchCV

In [25]:
pg={"n_neighbors":np.arange(1,30)}
gsm1=GridSearchCV(knn,param_grid=pg)
gsm1.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])})

In [26]:
yp1=gsm1.predict(x_test)
conf_matrix=confusion_matrix(y_test,yp1)
accuracy=accuracy_score(y_test,yp1)
print(accuracy)

0.9942528735632183

In [27]:
c_report=classification_report(y_test,yp1)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       430
           1       0.99      1.00      0.99       440

    accuracy                           0.99       870
   macro avg       0.99      0.99      0.99       870
weighted avg       0.99      0.99      0.99       870

In [28]:
conf_matrix=confusion_matrix(y_test,yp1)
print(conf_matrix)

[[427   3]
 [  2 438]]

In [29]:
from sklearn.naive_bayes import GaussianNB

In [30]:
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [31]:
y_predict=model.predict(x_test)

In [32]:
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)

0.9379310344827586

In [33]:
c_report=classification_report(y_test,y_predict)
print(c_report)

              precision    recall  f1-score   support

           0       0.89      1.00      0.94       430
           1       1.00      0.88      0.93       440

    accuracy                           0.94       870
   macro avg       0.94      0.94      0.94       870
weighted avg       0.94      0.94      0.94       870

In [34]:
conf_matrix=confusion_matrix(y_test,y_predict)
print(conf_matrix)

[[430   0]
 [ 54 386]]

In [35]:
from sklearn.model_selection import GridSearchCV

In [36]:
par_G={'var_smoothing':[1e-9,1e-8,1e-7,1e-6,1e-5]}
gsm=GridSearchCV(estimator=model,param_grid=par_G)
gsm.fit(x_train,y_train)

GridSearchCV(estimator=GaussianNB(),
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07, 1e-06, 1e-05]})

In [37]:
y_predict=gsm.predict(x_test)

In [38]:
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)

0.9379310344827586

In [39]:
c_report=classification_report(y_test,y_predict)
print(c_report)

              precision    recall  f1-score   support

           0       0.89      1.00      0.94       430
           1       1.00      0.88      0.93       440

    accuracy                           0.94       870
   macro avg       0.94      0.94      0.94       870
weighted avg       0.94      0.94      0.94       870

In [40]:
conf_matrix=confusion_matrix(y_test,y_predict)
print(conf_matrix)

[[430   0]
 [ 54 386]]

In [41]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [42]:
lg.fit(x_train,y_train)

LogisticRegression()

In [43]:
lg_p=lg.predict(x_test)

In [44]:
accuracy=accuracy_score(y_test,lg_p)
print(accuracy)

0.9977011494252873

In [45]:
c_report=classification_report(y_test,lg_p)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [46]:
conf_matrix=confusion_matrix(y_test,lg_p)
print(conf_matrix)

[[429   1]
 [  1 439]]

In [47]:
pg={"max_iter":[100,200]}
gsm3=GridSearchCV(lg,pg)
gsm3.fit(x_train,y_train)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'max_iter': [100, 200]})

In [48]:
y_predict=gsm3.predict(x_test)

In [49]:
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)

0.9977011494252873

In [50]:
c_report=classification_report(y_test,y_predict)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [51]:
conf_matrix=confusion_matrix(y_test,y_predict)
print(conf_matrix)

[[429   1]
 [  1 439]]

In [52]:
from sklearn.tree import DecisionTreeClassifier,plot_tree

In [53]:
model2=DecisionTreeClassifier(random_state=0)

In [54]:
model2.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [55]:
y2_predict=model2.predict(x_test)

In [56]:
accuracy=accuracy_score(y_test,y2_predict)
print(accuracy)

0.996551724137931

In [57]:
c_report=classification_report(y_test,y2_predict)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [58]:
conf_matrix=confusion_matrix(y_test,y2_predict)
conf_matrix

array([[428,   2],
       [  1, 439]])

In [61]:
pg={'criterion':['gini','entropy'],'max_depth':[None,10,20,30,40,50],'min_samples_split':[2,5,10],'min_samples_leaf':[1,2,4]}
gsm1=GridSearchCV(estimator=model2,param_grid=pg)
gsm1.fit(x_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 10, 20, 30, 40, 50],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

In [62]:
yp=gsm1.predict(x_test)
conf_matrix=confusion_matrix(y_test,yp)
accuracy=accuracy_score(y_test,yp)
print(accuracy)

0.9988505747126437

In [63]:
c_report=classification_report(y_test,yp)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [64]:
conf_matrix=confusion_matrix(y_test,yp)
conf_matrix

array([[430,   0],
       [  1, 439]])

In [65]:
from sklearn.ensemble import RandomForestClassifier

In [66]:
model2=RandomForestClassifier()

In [67]:
model2.fit(x_train,y_train)

RandomForestClassifier()

In [68]:
y2_predict=model2.predict(x_test)

In [69]:
accuracy=accuracy_score(y_test,y2_predict)
print(accuracy)

0.9988505747126437

In [70]:
c_report=classification_report(y_test,y2_predict)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [71]:
conf_matrix=confusion_matrix(y_test,y2_predict)
conf_matrix

array([[430,   0],
       [  1, 439]])

In [72]:
pg={'criterion':['gini','entropy'],'max_depth':[None,10,20,30,40,50],'min_samples_split':[2,5,10],'min_samples_leaf':[1,2,4]}
gsm1=GridSearchCV(estimator=model2,param_grid=pg)
gsm1.fit(x_train,y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 10, 20, 30, 40, 50],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

In [73]:
yp=gsm1.predict(x_test)
conf_matrix=confusion_matrix(y_test,yp)
accuracy=accuracy_score(y_test,yp)
print(accuracy)

0.9977011494252873

In [74]:
c_report=classification_report(y_test,yp)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [75]:
conf_matrix=confusion_matrix(y_test,yp)
conf_matrix

array([[429,   1],
       [  1, 439]])

In [76]:
from sklearn.svm import SVC
classifier= SVC()

In [77]:
classifier.fit(x_train,y_train)

SVC()

In [78]:
yp=classifier.predict(x_test)

In [79]:
accuracy_score(y_test,yp)

0.9942528735632183

In [80]:
confusion_matrix(y_test,yp)

array([[426,   4],
       [  1, 439]])

In [81]:
c_report=classification_report(y_test,yp)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       430
           1       0.99      1.00      0.99       440

    accuracy                           0.99       870
   macro avg       0.99      0.99      0.99       870
weighted avg       0.99      0.99      0.99       870

In [82]:
import numpy as np
from sklearn.model_selection import GridSearchCV
pg={'C':[0.1,1,10],'kernel':['linear']}
gsm5=GridSearchCV(estimator=classifier,param_grid=pg,cv=5)
gsm5.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10], 'kernel': ['linear']})

In [83]:
yp=gsm5.predict(x_test)
conf_matrix=confusion_matrix(y_test,yp)
accuracy=accuracy_score(y_test,yp)
print(accuracy)

0.9977011494252873

In [84]:
c_report=classification_report(y_test,yp)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [85]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier,plot_tree

In [86]:
BE=DecisionTreeClassifier(random_state=0)
bcm=BaggingClassifier(estimator=BE,n_estimators=10,random_state=0)
bcm.fit(x_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(random_state=0),
                  random_state=0)

In [87]:
lg_p=bcm.predict(x_test)
#conf_matrix=confusion_matrix(y_test,lg_p)
accuracy=accuracy_score(y_test,lg_p)
print(accuracy)

0.996551724137931

In [88]:
c_report=classification_report(y_test,lg_p) 
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [89]:
lg_m3=confusion_matrix(lg_p,y_test)
lg_m3

array([[428,   1],
       [  2, 439]])

In [90]:
BE=KNeighborsClassifier(n_neighbors=7)
bcm=BaggingClassifier(estimator=BE,n_estimators=10,random_state=0)
bcm.fit(x_train,y_train)

BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=7), random_state=0)

In [91]:
lg_p=bcm.predict(x_test)
#conf_matrix=confusion_matrix(y_test,lg_p)
accuracy=accuracy_score(y_test,lg_p)
print(accuracy)

0.9942528735632183

In [92]:
c_report=classification_report(y_test,lg_p) 
print(c_report)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       430
           1       1.00      0.99      0.99       440

    accuracy                           0.99       870
   macro avg       0.99      0.99      0.99       870
weighted avg       0.99      0.99      0.99       870

In [93]:
lg_m3=confusion_matrix(lg_p,y_test)
lg_m3

array([[428,   3],
       [  2, 437]])

In [94]:
from sklearn.ensemble import GradientBoostingClassifier

gbm = GradientBoostingClassifier(n_estimators=10,learning_rate=0.1, random_state=0)
gbm.fit(x_train, y_train)

GradientBoostingClassifier(n_estimators=10, random_state=0)

In [95]:
p6=gbm.predict(x_test)

In [96]:
c_report=classification_report(y_test,p6) 
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [97]:
from sklearn.model_selection import GridSearchCV
pg={'n_estimators':[50,100,200],'learning_rate':[0.1,0.05,0.01],'max_depth':[3,4,5]}
gsm6=GridSearchCV(estimator=gbm,param_grid=pg,cv=5)
gsm6.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=GradientBoostingClassifier(n_estimators=10,
                                                  random_state=0),
             param_grid={'learning_rate': [0.1, 0.05, 0.01],
                         'max_depth': [3, 4, 5],
                         'n_estimators': [50, 100, 200]})

In [98]:
yp=gsm1.predict(x_test)
conf_matrix=confusion_matrix(y_test,yp)
accuracy=accuracy_score(y_test,yp)
print(accuracy)

0.9977011494252873

In [99]:
c_report=classification_report(y_test,yp)
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [100]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression

In [101]:
f1=LogisticRegression(max_iter=100,random_state=0)
f2=DecisionTreeClassifier(random_state=0)
f3=SVC(kernel='linear',random_state=0)
vcm=VotingClassifier(estimators=[('lr',f1),('dt',f2),('svm',f3)],voting='hard')

In [102]:
vcm.fit(x_train,y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=0)),
                             ('dt', DecisionTreeClassifier(random_state=0)),
                             ('svm', SVC(kernel='linear', random_state=0))])

In [103]:
lg_p=vcm.predict(x_test)
#conf_matrix=confusion_matrix(y_test,lg_p)
accuracy=accuracy_score(y_test,lg_p)
print(accuracy)

0.9977011494252873

In [104]:
c_report=classification_report(y_test,lg_p) 
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [105]:
lg_m3=confusion_matrix(lg_p,y_test)
lg_m3

array([[429,   1],
       [  1, 439]])

In [106]:
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import RandomForestClassifier

In [107]:
a=RandomForestClassifier(n_estimators=10,random_state=0)
b=GradientBoostingClassifier(n_estimators=10,random_state=0)
c=SVC(kernel='linear',random_state=0)
base_models=[('rf',a),('gb',b),('SVC',c)]

In [108]:
meta_m= LogisticRegression(random_state=0)

In [109]:
scm=StackingClassifier(estimators=base_models,final_estimator=meta_m)

In [110]:
scm.fit(x_train,y_train)

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(n_estimators=10,
                                                       random_state=0)),
                               ('gb',
                                GradientBoostingClassifier(n_estimators=10,
                                                           random_state=0)),
                               ('SVC', SVC(kernel='linear', random_state=0))],
                   final_estimator=LogisticRegression(random_state=0))

In [111]:
lg_p=scm.predict(x_test)
#conf_matrix=confusion_matrix(y_test,lg_p)
accuracy=accuracy_score(y_test,lg_p)
print(accuracy)

0.9977011494252873

In [112]:
c_report=classification_report(y_test,lg_p) 
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [113]:
lg_m3=confusion_matrix(lg_p,y_test)
lg_m3

array([[429,   1],
       [  1, 439]])

In [114]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [115]:
adbo=AdaBoostClassifier(DecisionTreeClassifier(),n_estimators=44)

In [116]:
adbo.fit(x_train,y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(), n_estimators=44)

In [117]:
lg_p=adbo.predict(x_test)
#conf_matrix=confusion_matrix(y_test,lg_p)
accuracy=accuracy_score(y_test,lg_p)
print(accuracy)

0.996551724137931

In [118]:
c_report=classification_report(y_test,lg_p) 
print(c_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       430
           1       1.00      1.00      1.00       440

    accuracy                           1.00       870
   macro avg       1.00      1.00      1.00       870
weighted avg       1.00      1.00      1.00       870

In [119]:
lg_m3=confusion_matrix(lg_p,y_test)
lg_m3

array([[428,   1],
       [  2, 439]])

In [120]:
data={
    "Algorithms":['Logistic Regression','Decision Tree','Random Forest','Naive Bayes','KNN','SVM','Bagging','Boosting','VotingClassifier','StackingClassifier','AdaBoostClassifier'],
    "Accuracy(%)":[99,99,99,94,99,99,99,99,99,99,99],
    "Precision(%)":[99,99,99,94,99,99,99,99,99,99,99],
    "Recall(%)":[99,99,99,94,99,99,99,99,99,99,99],
    "f1-score (%)":[99,99,99,94,99,99,99,99,99,99,99]
    }
data = pd.DataFrame(data)
data1 = data.melt(id_vars='Algorithms',var_name='Metric',value_name='Score')
data

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4215452014.py, line 5)